font:
  size: 7.0
  normal:
    family: hack nerd font

schemes:
  som: &som
    primary:
      background: "#1d1f21"
      foreground: "#c5c8c6"
    cursor:
      text: CellBackground
      cursor: "#d7d7d7"
    selection:
      text: CellForeground
      background: "#3e4451"

    # Normal colors
    normal:
      black:   "#282a2e"
      red:     "#a54242"
      green:   "#8c9440"
      yellow:  "#de935f"
      blue:    "#5f819d"
      magenta: "#85678f"
      cyan:    "#5e8d87"
      white:   "#707880"

    # Bright colors
    bright:
      black:   "#373b41"
      red:     "#cc6666"
      green:   "#b5bd68"
      yellow:  "#f0c674"
      blue:    "#81a2be"
      magenta: "#b294bb"
      cyan:    "#8abeb7"
      white:   "#c5c8c6"

  one: &one
    primary:
      background: '#282c34'
      foreground: '#abb2bf'
    cursor:
      text:       CellBackground
      cursor:     '#be5046' # syntax-cursor-color
    selection:
      text:       CellForeground
      background: '#5c6370' # syntax-selection-color

    bright:
      black:      '#5c6370' # mono-3
      red:        '#be5046' # red 1
      green:      '#7a9f60'
      yellow:     '#d19a66' # orange 2
      blue:       '#3b84c0'
      magenta:    '#9a52af'
      cyan:       '#3c909b'
      white:      '#828997' # mono-2
    normal:
      black:      '#282c34' # mono-3
      red:        '#e06c75' # red 1
      green:      '#98c379'
      yellow:     '#e5c07b' # orange 2
      blue:       '#61afef'
      magenta:    '#c678dd'
      cyan:       '#56b6c2'
      white:      '#abb2bf' # mono-2

    gruv: &gruv
      # Default colors
      primary:
        background: '0x1d2021'
        foreground: '0xd5c4a1'

      # Colors the cursor will use if `custom_cursor_colors` is true
      cursor:
        text: '0x1d2021'
        cursor: '0xd5c4a1'

      # Normal colors
      normal:
        black:   '0x1d2021'
        red:     '0xfb4934'
        green:   '0xb8bb26'
        yellow:  '0xfabd2f'
        blue:    '0x83a598'
        magenta: '0xd3869b'
        cyan:    '0x8ec07c'
        white:   '0xd5c4a1'

      # Bright colors
      bright:
        black:   '0x665c54'
        red:     '0xfb4934'
        green:   '0xb8bb26'
        yellow:  '0xfabd2f'
        blue:    '0x83a598'
        magenta: '0xd3869b'
        cyan:    '0x8ec07c'
        white:   '0xfbf1c7'      

    xcode: &xcode
      primary:
        background: '#292c36'

      normal:
        black: '#494d5c'
        red: '#bb383a'
        green: '#94c66e'
        yellow: '#d28e5d'
        blue: '#8884c5'
        magenta: '#b73999'
        cyan: '#00aba4'
        white: '#e7e8eb'

      bright:
        black: '#7f869e'
        red: '#bb383a'
        green: '#94c66e'
        yellow: '#d28e5d'
        blue: '#8884c5'
        magenta: '#b73999'
        cyan: '#00aba4'
        white: '#e7e8eb'

    iterm: &iterm
      # Default colors
      primary:
        background: '0x101421'
        foreground: '0xfffbf6'

      # Normal colors
      normal:
        black:   '0x2e2e2e'
        red:     '0xeb4129'
        green:   '0xabe047'
        yellow:  '0xf6c744'
        blue:    '0x47a0f3'
        magenta: '0x7b5cb0'
        cyan:    '0x64dbed'
        white:   '0xe5e9f0'

      # Bright colors
      bright:
        black:   '0x565656'
        red:     '0xec5357'
        green:   '0xc0e17d'
        yellow:  '0xf9da6a'
        blue:    '0x49a4f8'
        magenta: '0xa47de9'
        cyan:    '0x99faf2'
        white:   '0xffffff'

    dark: &dark
      primary:
        foreground: '0xdbdbdb'
        background: '0x14191e'
      cursor:
        text: '0x000000'
        cursor: '0xfefffe'
      selection:
        text: '0x000000'
        background: '0xb3d7ff'
      normal:
        black:   '0x14191e'
        red:     '0xb43c29'
        green:   '0x00c200'
        yellow:  '0xc7c400'
        blue:    '0x2743c7'
        magenta: '0xbf3fbd'
        cyan:    '0x00c5c7'
        white:   '0xc7c7c7'
      bright:
        black:   '0x676767'
        red:     '0xdc7974'
        green:   '0x57e690'
        yellow:  '0xece100'
        blue:    '0xa6aaf1'
        white:   '0xfeffff'

    julie: &julie
      primary:
        foreground: '#c6a57b'
        background: '#151515'
      
      normal:
        black: '#151515'
        red: '#953331'
        green: '#546a29'
        yellow: '#999737'
        blue: '#385e6b'
        magenta: '#7f355e'
        cyan: '#34676f'
        white: '#c6a57b'
      bright:
        black: '#202020'
        red: '#8d4a4a'
        green: '#7e9960'
        yellow: '#ff8939'
        blue: '#5c737c'
        magenta: '#7f355e'
        cyan: '#34676f'
        white: '#c6a57b'

    gruvbox_material_hard_dark: &gruvbox_material_hard_dark
      primary:
        background: '0x1d2021'
        foreground: '0xd4be98'
      normal:
        black:   '0x32302f'
        red:     '0xea6962'
        green:   '0xa9b665'
        yellow:  '0xd8a657'
        blue:    '0x7daea3'
        magenta: '0xd3869b'
        cyan:    '0x89b482'
        white:   '0xd4be98'
      bright:
        black:   '0x32302f'
        red:     '0xea6962'
        green:   '0xa9b665'
        yellow:  '0xd8a657'
        blue:    '0x7daea3'
        magenta: '0xd3869b'
        cyan:    '0x89b482'
        white:   '0xd4be98'

    iceberg: &iceberg
      primary:
        background: '0x16171E'
        foreground: '0xD1D2D3'

      cursor:
        text: '0xFEFFFF'
        cursor: '0xc7c7c7'

      # Normal colors
      normal:
        black: '0x000000'
        red: '0xE68E8E'
        green: '0x83AC8E'
        yellow: '0xF5B78A'
        blue: '0x9BB8DC'
        magenta: '0xBAACE2'
        cyan: '0x00C5C7'
        white: '0xC7C7C7'

      # Bright colors
      bright:
        black: '0x676767'
        red: '0xFF6D67'
        green: '0x5FF967'
        yellow: '0xFEFB67'
        blue: '0x6871FF'
        magenta: '0xFF76FF'
        cyan: '0x5FFDFF'
        white: '0xFEFFFF'

        

colors: *dark

window:
  dynamic_padding: true
  opacity: 1
TERM: xterm-256color
